### ISSUE TITLE
wad assignment 3-4

### ISSUE THREAD

**Issue by shoaibrazzaq** [shoaibrazzaq/assignment3-4#1]
task assign
-[ ]made a simple html front end of smart device repair 
-[ ] create every page and connect it action to other pages
-[ ]create form of smart device repair where user is entering the data

**Comment by l1s16bscs0021** [comment]
[smartrepairer.zip](https://github.com/shoaibrazzaq/assignment3-4/files/2809009/smartrepairer.zip)
